CREATE TABLE IF NOT EXISTS USERS ( 
UID VARCHAR(255) PRIMARY KEY, 
PWD TEXT NOT NULL, 
BALANCE FLOAT NOT NULL, 
TOKEN TEXT, 
TERMINAL TEXT 
);

CREATE TABLE IF NOT EXISTS SHOPS ( 
SHOP_ID VARCHAR(255) PRIMARY KEY, 
UID VARCHAR(255) NOT NULL,
FOREIGN KEY (UID)
REFERENCES users (UID)
ON UPDATE CASCADE ON DELETE CASCADE,
RANKING INTEGER
);

CREATE TABLE IF NOT EXISTS BOOKS ( 
BOOK_ID TEXT,
SHOP_ID VARCHAR(255),
PRIMARY KEY(BOOK_ID, SHOP_ID),
FOREIGN KEY (SHOP_ID)
REFERENCES shops (SHOP_ID)
ON UPDATE CASCADE ON DELETE CASCADE,
QUANTITY INTEGER NOT NULL, 
title TEXT, 
author TEXT, 
publisher TEXT, 
original_title TEXT, 
translator TEXT, 
pub_year TEXT, 
pages INTEGER, 
price INTEGER, 
currency_unit TEXT, 
binding TEXT, 
isbn TEXT, 
author_intro TEXT, 
book_intro TEXT, 
content TEXT, 
tags TEXT,
pictures TEXT
);

CREATE TABLE IF NOT EXISTS ORDERS (
ORDER_ID TEXT PRIMARY KEY, 
UID VARCHAR(255) NOT NULL,
SHOP_ID VARCHAR(255) NOT NULL, 
ORDER_TIME TEXT NOT NULL, 
CURRENT_STATE INTEGER NOT NULL,
FOREIGN KEY (UID)
REFERENCES USERS (UID)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (SHOP_ID)
REFERENCES SHOPS (SHOP_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ORDER_BOOK (
ORDER_ID TEXT, 
BOOK_ID TEXT NOT NULL,
PRIMARY KEY (ORDER_ID, BOOK_ID),
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS (ORDER_ID)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (BOOK_ID)
REFERENCES BOOKS (BOOK_ID)
ON UPDATE CASCADE ON DELETE CASCADE,
ORDER_QUANTITY INTEGER NOT NULL
);